//! Build script to pre-compile Aptos Move contracts at build time
//!
//! This script compiles CSV Move modules using the Aptos Move compiler
//! and embeds the bytecode as constants for runtime deployment.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=contracts/csv_seal.move");
    println!("cargo:rerun-if-changed=contracts/Move.toml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let contracts_dir = Path::new("contracts");
    let bytecode_out = PathBuf::from(&out_dir);

    // Try to compile with aptos CLI if available
    if has_aptos_cli() {
        println!("cargo:warning=Aptos CLI detected, compiling Move modules...");
        compile_with_aptos(contracts_dir);
    } else {
        println!("cargo:warning=Aptos CLI not found, checking for pre-compiled bytecode...");
    }

    // Generate bytecode constants
    generate_bytecode_constants(&bytecode_out, contracts_dir);
}

fn has_aptos_cli() -> bool {
    Command::new("aptos")
        .arg("--version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn compile_with_aptos(contracts_dir: &Path) {
    let output = Command::new("aptos")
        .args(&["move", "compile"])
        .current_dir(contracts_dir)
        .output()
        .expect("Failed to execute aptos move compile");

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        println!("cargo:warning=Aptos move compile failed: {}", stderr);
    } else {
        println!("cargo:warning=Move modules compiled successfully");
    }
}

fn generate_bytecode_constants(bytecode_out: &Path, contracts_dir: &Path) {
    let mut code = String::new();

    code.push_str("// Auto-generated by build.rs - do not edit\n");
    code.push_str("// This file contains embedded Aptos Move bytecode\n\n");

    // Try to read compiled bytecode from build directory
    let bytecode = read_move_bytecode(contracts_dir);

    code.push_str("/// CSV seal Move module bytecode (pre-compiled at build time)\n");
    code.push_str(&format!(
        "pub const CSV_SEAL_BYTECODE: &[u8] = &[{}];\n\n",
        bytecode
    ));

    // Write to OUT_DIR
    let dest_path = bytecode_out.join("aptos_bytecode.rs");
    fs::write(&dest_path, code).expect("Failed to write bytecode constants");

    println!(
        "cargo:warning=Generated Aptos bytecode constants at: {:?}",
        dest_path
    );
}

fn read_move_bytecode(contracts_dir: &Path) -> String {
    let build_dir = contracts_dir.join("build");
    if let Some(path) = find_first_file_with_extension(&build_dir, "mv") {
        let bytes = fs::read(&path)
            .unwrap_or_else(|err| panic!("Failed to read Aptos Move bytecode {:?}: {}", path, err));
        return bytes_to_array_literal(&bytes);
    }

    panic!(
        "Aptos Move bytecode not found under {:?}. Run `aptos move compile` in csv-adapter-aptos/contracts or commit precompiled .mv artifacts.",
        build_dir
    );
}

fn find_first_file_with_extension(dir: &Path, extension: &str) -> Option<PathBuf> {
    let entries = fs::read_dir(dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(found) = find_first_file_with_extension(&path, extension) {
                return Some(found);
            }
        } else if path.extension().map_or(false, |e| e == extension) {
            return Some(path);
        }
    }
    None
}

fn bytes_to_array_literal(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ")
}
