//! Build script to pre-compile Solana programs at build time
//!
//! This script compiles CSV Anchor programs using anchor build
//! and embeds the bytecode as constants for runtime deployment.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=contracts/programs/");
    println!("cargo:rerun-if-changed=contracts/Anchor.toml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let contracts_dir = Path::new("contracts");
    let bytecode_out = PathBuf::from(&out_dir);

    // Try to compile with anchor CLI if available
    if has_anchor_cli() {
        println!("cargo:warning=Anchor CLI detected, compiling programs...");
        compile_with_anchor(contracts_dir);
    } else {
        println!("cargo:warning=Anchor CLI not found, checking for pre-compiled bytecode...");
    }

    // Generate bytecode constants
    generate_bytecode_constants(&bytecode_out, contracts_dir);
}

fn has_anchor_cli() -> bool {
    Command::new("anchor")
        .arg("--version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn compile_with_anchor(contracts_dir: &Path) {
    let output = Command::new("anchor")
        .args(&["build"])
        .current_dir(contracts_dir)
        .output()
        .expect("Failed to execute anchor build");

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        println!("cargo:warning=Anchor build failed: {}", stderr);
    } else {
        println!("cargo:warning=Programs compiled successfully");
    }
}

fn generate_bytecode_constants(bytecode_out: &Path, contracts_dir: &Path) {
    let mut code = String::new();

    code.push_str("// Auto-generated by build.rs - do not edit\n");
    code.push_str("// This file contains embedded Solana program bytecode\n\n");

    // Try to read compiled bytecode from target directory
    let bytecode = read_program_bytecode(contracts_dir);

    code.push_str("/// CSV seal Solana program bytecode (pre-compiled at build time)\n");
    code.push_str(&format!(
        "pub const CSV_SEAL_PROGRAM: &[u8] = &[{}];\n\n",
        bytecode
    ));

    // Write to OUT_DIR
    let dest_path = bytecode_out.join("solana_bytecode.rs");
    fs::write(&dest_path, code).expect("Failed to write bytecode constants");

    println!(
        "cargo:warning=Generated Solana bytecode constants at: {:?}",
        dest_path
    );
}

fn read_program_bytecode(contracts_dir: &Path) -> String {
    // Look for compiled .so files in target/deploy
    let deploy_dir = contracts_dir.join("target/deploy");
    if deploy_dir.exists() {
        if let Ok(entries) = fs::read_dir(&deploy_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().map_or(false, |e| e == "so") {
                    if let Ok(bytes) = fs::read(&path) {
                        return bytes_to_array_literal(&bytes);
                    }
                }
            }
        }
    }

    panic!(
        "Solana program bytecode not found under {:?}. Run `anchor build` in csv-adapter-solana/contracts or commit precompiled .so artifacts.",
        deploy_dir
    );
}

fn bytes_to_array_literal(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ")
}
