//! Build script to pre-compile Solana programs at build time
//!
//! This script compiles CSV Anchor programs using anchor build
//! and embeds the bytecode as constants for runtime deployment.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=contracts/programs/");
    println!("cargo:rerun-if-changed=contracts/Anchor.toml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let contracts_dir = Path::new("contracts");
    let bytecode_out = PathBuf::from(&out_dir);

    // Try to compile with anchor CLI if available
    if has_anchor_cli() {
        println!("cargo:warning=Anchor CLI detected, compiling programs...");
        compile_with_anchor(contracts_dir);
    } else {
        println!("cargo:warning=Anchor CLI not found, checking for pre-compiled bytecode...");
    }

    // Generate bytecode constants
    generate_bytecode_constants(&bytecode_out, contracts_dir);
}

fn has_anchor_cli() -> bool {
    Command::new("anchor")
        .arg("--version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn compile_with_anchor(contracts_dir: &Path) {
    let output = Command::new("anchor")
        .args(["build"])
        .current_dir(contracts_dir)
        .output()
        .expect("Failed to execute anchor build");

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        println!("cargo:warning=Anchor build failed: {}", stderr);
    } else {
        println!("cargo:warning=Programs compiled successfully");
    }
}

fn generate_bytecode_constants(bytecode_out: &Path, contracts_dir: &Path) {
    let mut code = String::new();

    code.push_str("// Auto-generated by build.rs - do not edit\n");
    code.push_str("// This file contains embedded Solana program bytecode\n\n");

    // Try to read compiled bytecode from target directory
    let bytecode = read_program_bytecode(contracts_dir);

    code.push_str("/// CSV seal Solana program bytecode (pre-compiled at build time)\n");
    code.push_str(&format!(
        "pub const CSV_SEAL_PROGRAM: &[u8] = &[{}];\n\n",
        bytecode
    ));

    // Write to OUT_DIR
    let dest_path = bytecode_out.join("solana_bytecode.rs");
    fs::write(&dest_path, code).expect("Failed to write bytecode constants");

    println!(
        "cargo:warning=Generated Solana bytecode constants at: {:?}",
        dest_path
    );
}

fn read_program_bytecode(contracts_dir: &Path) -> String {
    // Look for compiled .so files in target/deploy (Anchor < 0.30)
    // or programs/<program>/target/deploy (Anchor >= 0.30)
    let deploy_dir = contracts_dir.join("target/deploy");
    let program_deploy_dir = contracts_dir.join("programs/csv-seal/target/deploy");

    let search_dirs = vec![&deploy_dir, &program_deploy_dir];

    for dir in &search_dirs {
        if dir.exists() {
            if let Ok(entries) = fs::read_dir(dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.extension().is_some_and(|e| e == "so") {
                        if let Ok(bytes) = fs::read(&path) {
                            return bytes_to_array_literal(&bytes);
                        }
                    }
                }
            }
        }
    }

    // CRITICAL FIX: Instead of panicking (which blocks `cargo check --workspace`),
    // emit a placeholder and a warning. The program ID mismatch between Anchor.toml
    // and source code has been resolved (both now use HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD).
    // Pre-compiled .so artifacts can be committed manually, or `anchor build` can be run.
    println!("cargo:warning=Solana program bytecode not found under {:?} or {:?}.", deploy_dir, program_deploy_dir);
    println!("cargo:warning=Run `anchor build` in contracts/ to compile programs.");
    println!("cargo:warning=Using empty placeholder - runtime deployment will need actual bytecode.");
    String::new() // Empty placeholder - callers must handle missing bytecode
}

fn bytes_to_array_literal(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ")
}
