//! Contract bytecode for CSV Ethereum contracts
//!
//! This module provides access to compiled contract bytecode.
//! 
//! # Bytecode Sources
//! - Build time: Generated by build.rs using `forge build`
//! - Fallback: Pre-compiled bytecode can be embedded here
//!
//! # Usage
//! The bytecode constants are used by the deployment functions in `ops.rs`.

/// CSVLock contract bytecode placeholder
/// 
/// # IMPORTANT
/// This is a placeholder. For actual deployment:
/// 1. Run `forge build` in `csv-adapter/csv-ethereum/contracts`
/// 2. The build.rs script will generate bytecode at build time
/// 3. Or replace this with actual compiled bytecode
///
/// To generate:
/// ```bash
/// cd csv-ethereum/contracts
/// forge build
/// ```
pub const CSVLOCK_BYTECODE: &[u8] = &[];

/// CSVMint contract bytecode placeholder
/// 
/// # IMPORTANT  
/// This is a placeholder. See CSVLOCK_BYTECODE for instructions.
pub const CSVMINT_BYTECODE: &[u8] = &[];

/// Contract initialization parameters
pub struct ContractInitParams {
    /// Admin address for the contract
    pub admin: String,
    /// Initial refund timeout in seconds (default: 86400 = 24 hours)
    pub refund_timeout: u64,
}

impl Default for ContractInitParams {
    fn default() -> Self {
        Self {
            admin: String::new(),
            refund_timeout: 86400,
        }
    }
}

/// Build deployment transaction data (constructor args + bytecode)
pub fn build_deploy_tx_data(bytecode: &[u8], _params: &ContractInitParams) -> Vec<u8> {
    // For CSVLock, the constructor doesn't take arguments
    // Future: ABI-encode constructor arguments if needed
    bytecode.to_vec()
}
