//! Ethereum Adapter for CSV (Client-Side Validation)
//!
//! This adapter implements the SealProtocol trait for Ethereum,
//! using storage slots as single-use seals and LOG events for commitment publication.

#![warn(missing_docs)]
#![allow(missing_docs)]

// Include pre-compiled contract bytecode generated by build.rs (if available)
// If OUT_DIR/contract_bytecode.rs doesn't exist, use the local module
#[cfg(not(feature = "bytecode-from-build"))]
pub mod contract_bytecode;

#[cfg(not(feature = "bytecode-from-build"))]
pub use contract_bytecode::{CSVLOCK_BYTECODE, CSVMINT_BYTECODE};

#[cfg(feature = "bytecode-from-build")]
include!(concat!(env!("OUT_DIR"), "/contract_bytecode.rs"));

pub mod backend;
pub mod config;
pub mod deploy;
pub mod error;
pub mod finality;
pub mod mpt;
pub mod ops;
pub mod proofs;
pub mod rpc;
pub mod sanad_contract;
pub mod seal;
pub mod seal_contract;
pub mod seal_protocol;
pub mod signatures;
pub mod types;
pub mod zk_verifier;

#[cfg(feature = "rpc")]
pub mod node;

#[cfg(feature = "rpc")]
pub use node::{
    publish, publish_seal_consumption, verify_seal_consumption_in_receipt, AlloyRpcError,
    EthereumNode,
};

pub use backend::{create_ethereum_adapter, EthereumRpcClient, EthereumWallet};
pub use config::EthereumConfig;
#[cfg(feature = "rpc")]
pub use deploy::deploy_csv_lock;
#[cfg(not(feature = "rpc"))]
pub use deploy::deploy_csv_seal_contract;
pub use deploy::{calculate_contract_address, ContractDeployer, ContractDeployment};
pub use error::EthereumError;
pub use finality::{FinalityChecker, FinalityConfig};
pub use rpc::EthereumRpc;
#[cfg(test)]
pub use rpc::MockEthereumRpc;
pub use sanad_contract::{CsvLockAbi, CsvMintAbi, cross_chain_lock_signature, sanad_minted_signature, sanad_refunded_signature};
pub use seal_contract::CsvSealAbi;
pub use seal_protocol::EthereumSealProtocol;
pub use types::{
    EthereumCommitAnchor, EthereumFinalityProof, EthereumInclusionProof, EthereumSealPoint,
};
pub use zk_verifier::{
    generate_verifier_contract_bytecode, EthereumGroth16Verifier, SolidityGroth16Proof,
};

// Ops exports
pub use ops::EthereumBackend;
