//! Ethereum Adapter for CSV (Client-Side Validation)
//!
//! This adapter implements the SealProtocol trait for Ethereum,
//! using storage slots as single-use seals and LOG events for commitment publication.

#![warn(missing_docs)]
#![allow(missing_docs)]

// Include pre-compiled contract bytecode generated by build.rs
include!(concat!(env!("OUT_DIR"), "/contract_bytecode.rs"));

pub mod seal_protocol;
pub mod backend;
pub mod ops;
pub mod config;
pub mod deploy;
pub mod error;
pub mod finality;
pub mod mpt;
pub mod proofs;
pub mod rpc;
pub mod seal;
pub mod seal_contract;
pub mod signatures;
pub mod types;
pub mod zk_verifier;

#[cfg(feature = "rpc")]
pub mod node;

#[cfg(feature = "rpc")]
pub use node::{
    publish, publish_seal_consumption, verify_seal_consumption_in_receipt, AlloyRpcError,
    EthereumNode,
};

pub use seal_protocol::EthereumSealProtocol;
pub use backend::{create_ethereum_adapter, EthereumRpcClient, EthereumWallet};
pub use config::EthereumConfig;
#[cfg(feature = "rpc")]
pub use deploy::deploy_csv_lock;
#[cfg(not(feature = "rpc"))]
pub use deploy::deploy_csv_seal_contract;
pub use deploy::{calculate_contract_address, ContractDeployer, ContractDeployment};
pub use error::EthereumError;
pub use finality::{FinalityChecker, FinalityConfig};
pub use rpc::EthereumRpc;
#[cfg(test)]
pub use rpc::MockEthereumRpc;
pub use seal_contract::CsvSealAbi;
pub use types::{
    EthereumCommitAnchor, EthereumFinalityProof, EthereumInclusionProof, EthereumSealPoint,
};
pub use zk_verifier::{EthereumGroth16Verifier, SolidityGroth16Proof, generate_verifier_contract_bytecode};

// Ops exports
pub use ops::EthereumBackend;
