//! Build script to pre-compile Solidity contracts at build time
//!
//! This script compiles CSV contracts using foundry/forge at build time
//! and embeds the bytecode as constants for runtime deployment.
//!
//! If forge is not available, it will use pre-compiled bytecode from the out/ directory.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=contracts/src/CSVLock.sol");
    println!("cargo:rerun-if-changed=contracts/src/CSVMint.sol");
    println!("cargo:rerun-if-changed=contracts/foundry.toml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let contracts_dir = Path::new("contracts");
    let bytecode_out = PathBuf::from(&out_dir);

    // Try to compile with forge if available
    if has_forge() {
        println!("cargo:warning=Foundry detected, compiling contracts...");
        compile_with_forge(contracts_dir);
    } else {
        println!("cargo:warning=Foundry not found, checking for pre-compiled bytecode...");
    }

    // Generate bytecode constants
    generate_bytecode_constants(&bytecode_out, contracts_dir);
}

fn has_forge() -> bool {
    Command::new("forge")
        .arg("--version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn compile_with_forge(contracts_dir: &Path) {
    let output = Command::new("forge")
        .args(&["build", "--sizes"])
        .current_dir(contracts_dir)
        .output()
        .expect("Failed to execute forge build");

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        println!("cargo:warning=Forge build failed: {}", stderr);
    } else {
        println!("cargo:warning=Contracts compiled successfully");
    }
}

fn generate_bytecode_constants(bytecode_out: &Path, contracts_dir: &Path) {
    let mut code = String::new();

    code.push_str("// Auto-generated by build.rs - do not edit\n");
    code.push_str("// This file contains embedded contract bytecode\n\n");

    let csv_lock_bytecode = read_bytecode(
        contracts_dir.join("out/CSVLock.sol/CSVLock.json"),
        "CSVLOCK_BYTECODE",
    );

    let csv_mint_bytecode = read_bytecode(
        contracts_dir.join("out/CSVMint.sol/CSVMint.json"),
        "CSVMINT_BYTECODE",
    );

    code.push_str(&format!(
        "/// CSVLock contract bytecode (pre-compiled at build time)\n"
    ));
    code.push_str(&format!(
        "pub const CSVLOCK_BYTECODE: &[u8] = &[{}];\n\n",
        csv_lock_bytecode
    ));

    code.push_str(&format!(
        "/// CSVMint contract bytecode (pre-compiled at build time)\n"
    ));
    code.push_str(&format!(
        "pub const CSVMINT_BYTECODE: &[u8] = &[{}];\n\n",
        csv_mint_bytecode
    ));

    // Write to OUT_DIR
    let dest_path = bytecode_out.join("contract_bytecode.rs");
    fs::write(&dest_path, code).expect("Failed to write bytecode constants");

    println!(
        "cargo:warning=Generated bytecode constants at: {:?}",
        dest_path
    );
}

fn read_bytecode(path: PathBuf, name: &str) -> String {
    if path.exists() {
        // Read the compiled bytecode from Foundry output
        let content = fs::read_to_string(&path).unwrap_or_else(|_| "{}".to_string());

        // Parse JSON to extract bytecode
        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
            if let Some(bytecode) = json
                .get("bytecode")
                .and_then(|b| b.get("object"))
                .and_then(|o| o.as_str())
            {
                // Convert hex string to byte array literal
                return hex_to_byte_array(bytecode);
            }
        }
    }

    panic!(
        "{} not found at {:?}. Run `forge build` in csv-adapter-ethereum/contracts or commit precompiled Foundry artifacts.",
        name, path
    );
}

fn hex_to_byte_array(hex: &str) -> String {
    let hex = hex.strip_prefix("0x").unwrap_or(hex);
    let bytes: Vec<String> = hex
        .as_bytes()
        .chunks(2)
        .filter_map(|chunk| {
            if chunk.len() == 2 {
                let hex_pair = std::str::from_utf8(chunk).ok()?;
                let byte = u8::from_str_radix(hex_pair, 16).ok()?;
                Some(format!("0x{:02x}", byte))
            } else {
                None
            }
        })
        .collect();

    bytes.join(", ")
}
