[toolchain]
anchor_version = "1.0.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
csv_seal = "CCMF6BvAyTPNJAPtGMVJAR652Hv9VPy9NmVdgC9969dj"

[programs.localnet]
csv_seal = "HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD"

[programs.mainnet]
csv_seal = "HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD"

[programs.testnet]
csv_seal = "HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "bash ../scripts/initialize.sh"
lint = "cargo clippy"
test = "cargo test"

[hooks]
pre-commit = "cargo clippy"
pre-push = "cargo test"
