import * as vscode from "vscode";
import { ProofVisualizerPanel } from "./proof-visualizer";
import { isValidRightId } from "./utils";
import { extensionConfiguration } from "./configuration";

/**
 * Registers all CSV Adapter commands with the VS Code context.
 */
export function registerCommands(context: vscode.ExtensionContext): void {
  // CSV: Create Right
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.createRight", async () => {
      await createRightCommand();
    })
  );

  // CSV: Transfer Cross-Chain
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.transferCrossChain", async () => {
      await transferCrossChainCommand();
    })
  );

  // CSV: Inspect Proof
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.inspectProof", async () => {
      await inspectProofCommand(context);
    })
  );

  // CSV: Check Wallet Balance
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.checkBalance", async () => {
      await checkBalanceCommand(context);
    })
  );

  // CSV: Open Documentation
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.openDocumentation", async () => {
      await vscode.env.openExternal(vscode.Uri.parse("https://docs.csv.dev"));
    })
  );

  // CSV: Run Tutorial
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.runTutorial", async () => {
      await runTutorialCommand();
    })
  );

  // CSV: Copy Right ID
  context.subscriptions.push(
    vscode.commands.registerCommand("csv.copyRightId", async (rightId?: string) => {
      await copyRightIdCommand(rightId);
    })
  );
}

/**
 * Implements the "Create Right" command with an input form.
 */
async function createRightCommand(): Promise<void> {
  // Step 1: Select chain
  const config = extensionConfiguration.getConfig(
    vscode.workspace.getConfiguration().get("csv.chains") as string[] | undefined
      ? vscode.workspace.getConfiguration() as unknown as vscode.ExtensionContext
      : undefined as unknown as vscode.ExtensionContext
  );

  const chains = ["ethereum", "bitcoin", "aptos", "sui", "solana"];
  const selectedChain = await vscode.window.showQuickPick(chains, {
    placeHolder: "Select the chain for this Right",
    canPickMany: false,
  });

  if (!selectedChain) {
    return;
  }

  // Step 2: Select Right type
  const rightTypes = ["ownership", "transfer", "custom"];
  const selectedType = await vscode.window.showQuickPick(rightTypes, {
    placeHolder: "Select the Right type",
    canPickMany: false,
  });

  if (!selectedType) {
    return;
  }

  // Step 3: Enter owner address
  const ownerAddress = await vscode.window.showInputBox({
    prompt: "Enter the owner address",
    placeHolder: "0x...",
    validateInput: (value) => {
      if (!value || value.trim().length === 0) {
        return "Owner address is required";
      }
      if (!value.startsWith("0x")) {
        return "Address should start with 0x";
      }
      return undefined;
    },
  });

  if (!ownerAddress) {
    return;
  }

  // Step 4: Optional metadata
  const metadata = await vscode.window.showInputBox({
    prompt: "Enter metadata (optional, JSON format)",
    placeHolder: '{"key": "value"}',
  });

  // Create the Right
  const rightInfo = {
    chain: selectedChain,
    type: selectedType,
    owner: ownerAddress,
    metadata: metadata || "{}",
    createdAt: new Date().toISOString(),
  };

  // Output the generated code to a new file
  const document = await vscode.workspace.openTextDocument({
    content: generateRightCode(rightInfo),
    language: selectedChain === "bitcoin" ? "rust" : "typescript",
  });

  await vscode.window.showTextDocument(document);
  vscode.window.showInformationMessage(
    `Right template created for ${selectedChain} (${selectedType})`
  );
}

/**
 * Generates code for creating a Right based on the provided configuration.
 */
function generateRightCode(info: {
  chain: string;
  type: string;
  owner: string;
  metadata: string;
}): string {
  return `// csv: Create Right - ${info.chain} / ${info.type}
// Generated by CSV Adapter VS Code extension

async function createRight() {
  const client = await CsvClient.connect({
    network: "testnet",
    chains: ["${info.chain}"],
  });

  const right = await client.createRight({
    type: "${info.type}",
    chain: "${info.chain}",
    owner: "${info.owner}",
    metadata: ${info.metadata},
  });

  console.log("Right created:", right.id);
  return right;
}`;
}

/**
 * Implements the "Transfer Cross-Chain" wizard.
 */
async function transferCrossChainCommand(): Promise<void> {
  const chains = ["ethereum", "bitcoin", "aptos", "sui", "solana"];

  // Step 1: Source chain
  const fromChain = await vscode.window.showQuickPick(chains, {
    placeHolder: "Select source chain",
    canPickMany: false,
  });

  if (!fromChain) {
    return;
  }

  // Step 2: Destination chain
  const toChain = await vscode.window.showQuickPick(
    chains.filter((c) => c !== fromChain),
    {
      placeHolder: "Select destination chain",
      canPickMany: false,
    }
  );

  if (!toChain) {
    return;
  }

  // Step 3: Amount
  const amount = await vscode.window.showInputBox({
    prompt: "Enter transfer amount",
    placeHolder: "100",
    validateInput: (value) => {
      if (!value || isNaN(Number(value)) || Number(value) <= 0) {
        return "Please enter a valid positive number";
      }
      return undefined;
    },
  });

  if (!amount) {
    return;
  }

  // Step 4: Recipient address
  const recipient = await vscode.window.showInputBox({
    prompt: "Enter recipient address",
    placeHolder: "0x...",
    validateInput: (value) => {
      if (!value || value.trim().length === 0) {
        return "Recipient address is required";
      }
      return undefined;
    },
  });

  if (!recipient) {
    return;
  }

  // Generate transfer code
  const transferCode = `// csv: Cross-Chain Transfer - ${fromChain} -> ${toChain}
// Amount: ${amount}

async function transfer() {
  const client = await CsvClient.connect({
    network: "testnet",
    chains: ["${fromChain}", "${toChain}"],
  });

  const transfer = await client.transfer({
    from: "${fromChain}",
    to: "${toChain}",
    amount: ${amount},
    recipient: "${recipient}",
  });

  const proof = await transfer.submit();
  console.log("Transfer complete:", proof.rightId);
  return proof;
}`;

  const document = await vscode.workspace.openTextDocument({
    content: transferCode,
    language: "typescript",
  });

  await vscode.window.showTextDocument(document);
  vscode.window.showInformationMessage(
    `Transfer template created: ${fromChain} -> ${toChain} (${amount})`
  );
}

/**
 * Implements the "Inspect Proof" command.
 */
async function inspectProofCommand(context: vscode.ExtensionContext): Promise<void> {
  const editor = vscode.window.activeTextEditor;

  // Try to extract Right ID from selection or clipboard
  let rightId: string | undefined;

  if (editor && !editor.selection.isEmpty) {
    const selectedText = editor.document.getText(editor.selection);
    if (isValidRightId(selectedText)) {
      rightId = selectedText;
    }
  }

  if (!rightId) {
    rightId = await vscode.window.showInputBox({
      prompt: "Enter the Right ID to inspect",
      placeHolder: "0x...",
      validateInput: (value) => {
        if (!value || value.trim().length === 0) {
          return "Right ID is required";
        }
        if (!isValidRightId(value)) {
          return "Invalid Right ID format. Expected: 0x followed by 64 hex characters";
        }
        return undefined;
      },
    });
  }

  if (!rightId) {
    return;
  }

  // Open the proof visualizer
  ProofVisualizerPanel.createOrShow(context.extensionUri);

  vscode.window.showInformationMessage(`Inspecting proof: ${rightId.substring(0, 10)}...`);
}

/**
 * Implements the "Check Wallet Balance" command.
 */
async function checkBalanceCommand(context: vscode.ExtensionContext): Promise<void> {
  const config = extensionConfiguration.getConfig(context as never);
  const chains = config.chains;

  if (chains.length === 0) {
    vscode.window.showWarningMessage(
      "No chains configured. Set csv.chains in settings."
    );
    return;
  }

  const balanceInfo: string[] = [];

  for (const chain of chains) {
    // Simulated balance - in production, query actual chain
    const balance = (Math.random() * 1000).toFixed(4);
    balanceInfo.push(`${chain}: ${balance} ${chain.toUpperCase()}`);
  }

  const message = balanceInfo.join("\n");

  await vscode.window.showInformationMessage(
    "Wallet Balances",
    { modal: true, detail: message },
    "OK"
  );
}

/**
 * Implements the "Run Tutorial" command.
 */
async function runTutorialCommand(): Promise<void> {
  const tutorialContent = `# CSV Adapter Tutorial

## Step 1: Install the SDK

\`\`\`bash
npm install @csv-adapter/sdk
# or for Rust
cargo add csv-adapter
\`\`\`

## Step 2: Initialize the Client

\`\`\`typescript
import { CsvClient } from "@csv-adapter/sdk";

const client = await CsvClient.connect({
  network: "testnet",
  chains: ["ethereum", "aptos", "sui"],
});
\`\`\`

## Step 3: Create a Right

\`\`\`typescript
const right = await client.createRight({
  type: "ownership",
  chain: "ethereum",
  owner: "0xYourAddress",
});
\`\`\`

## Step 4: Cross-Chain Transfer

\`\`\`typescript
const transfer = await client.transfer({
  from: "ethereum",
  to: "aptos",
  amount: 100,
  recipient: "0xRecipientAddress",
});
\`\`\`

## Step 5: Verify Proof

\`\`\`typescript
const isValid = await client.verifyProof({
  proof: transfer.proof,
  expectedRoot: "0xMerkleRoot",
  chain: "aptos",
});
\`\`\`

For full documentation, visit https://docs.csv.dev`;

  const document = await vscode.workspace.openTextDocument({
    content: tutorialContent,
    language: "markdown",
  });

  await vscode.window.showTextDocument(document);
}

/**
 * Implements the "Copy Right ID" command.
 */
async function copyRightIdCommand(rightId?: string): Promise<void> {
  if (!rightId) {
    vscode.window.showWarningMessage("No Right ID provided to copy");
    return;
  }

  await vscode.env.clipboard.writeText(rightId);
  vscode.window.showInformationMessage(
    `Copied Right ID: ${rightId.substring(0, 10)}...`
  );
}
